
export const outcomeCategoryConstants = {
  ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',
  LOAD_CATEGORIES_SUCCESS: 'LOAD_CATEGORIES_SUCCESS',
  CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
  UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
  DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS'
};

export const userConstants = {
  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  LOGOUT: 'USERS_LOGOUT',

  GETALL_REQUEST: 'USERS_GETALL_REQUEST',
  GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
  GETALL_FAILURE: 'USERS_GETALL_FAILURE',
};

export const outcomeItemConstants = {
  ADD_OUTCOME_ITEM_SUCCESS: 'ADD_OUTCOME_ITEM_SUCCESS',
  LOAD_OUTCOME_ITEMS_SUCCESS: 'LOAD_OUTCOME_ITEMS_SUCCESS',
  CREATE_OUTCOME_ITEM_SUCCESS: 'CREATE_OUTCOME_ITEM_SUCCESS',
  UPDATE_OUTCOME_ITEM_SUCCESS: 'UPDATE_OUTCOME_ITEM_SUCCESS',
  DELETE_OUTCOME_ITEM_SUCCESS: 'DELETE_OUTCOME_ITEM_SUCCESS'
};


export const outcomeConstants = {
  ADD_OUTCOMES_SUCCESS: 'ADD_OUTCOMES_SUCCESS',
  LOAD_OUTCOMES_SUCCESS: 'LOAD_OUTCOMES_SUCCESS',
  LOAD_OUTCOME_SUCCESS: 'LOAD_OUTCOME_SUCCESS',
  CREATE_OUTCOME_SUCCESS: 'CREATE_OUTCOME_SUCCESS',
  UPDATE_OUTCOME_SUCCESS: 'UPDATE_OUTCOME_SUCCESS',
  DELETE_OUTCOME_SUCCESS: 'DELETE_OUTCOME_SUCCESS'
};




