/* SETTINGS */
export const CHANGE_LOCALE = 'CHANGE_LOCALE';

/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';

export const ADD_CATEGORY_SUCCESS= 'ADD_CATEGORY_SUCCESS';
export const LOAD_CATEGORIES= 'LOAD_CATEGORIES';
export const LOAD_CATEGORIES_SUCCESS= 'LOAD_CATEGORIES_SUCCESS';
export const SAVE_CATEGORY= 'SAVE_CATEGORY';
export const DELETE_CATEGORY= 'DELETE_CATEGORY';
export const CREATE_CATEGORY_SUCCESS= 'CREATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_SUCCESS= 'UPDATE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_SUCCESS= 'DELETE_CATEGORY_SUCCESS';


export const userConstants = {
  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  LOGOUT: 'USERS_LOGOUT',

  GETALL_REQUEST: 'USERS_GETALL_REQUEST',
  GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
  GETALL_FAILURE: 'USERS_GETALL_FAILURE',
};

export const outcomeItemConstants = {
  ADD_OUTCOME_ITEM_SUCCESS: 'ADD_OUTCOME_ITEM_SUCCESS',
  LOAD_OUTCOME_ITEMS_SUCCESS: 'LOAD_OUTCOME_ITEMS_SUCCESS',
  CREATE_OUTCOME_ITEM_SUCCESS: 'CREATE_OUTCOME_ITEM_SUCCESS',
  UPDATE_OUTCOME_ITEM_SUCCESS: 'UPDATE_OUTCOME_ITEM_SUCCESS',
  DELETE_OUTCOME_ITEM_SUCCESS: 'DELETE_OUTCOME_ITEM_SUCCESS'
};


export const outcomeConstants = {
  ADD_OUTCOMES_SUCCESS: 'ADD_OUTCOMES_SUCCESS',
  LOAD_OUTCOMES_SUCCESS: 'LOAD_OUTCOMES_SUCCESS',
  LOAD_OUTCOME_SUCCESS: 'LOAD_OUTCOME_SUCCESS',
  CREATE_OUTCOME_SUCCESS: 'CREATE_OUTCOME_SUCCESS',
  UPDATE_OUTCOME_SUCCESS: 'UPDATE_OUTCOME_SUCCESS',
  DELETE_OUTCOME_SUCCESS: 'DELETE_OUTCOME_SUCCESS'
};
